export const COLOMBIA_CITIES: string[] = [
  'Acacías', 'Aguachica', 'Aguadas', 'Aguazul', 'Albania', 'Andes', 'Anserma', 'Apartadó', 'Arauca', 'Armenia',
  'Barbosa', 'Barrancabermeja', 'Barranquilla', 'Bello', 'Bogotá', 'Bucaramanga', 'Buenaventura', 'Buga',
  'Caldas', 'Cali', 'Calarcá', 'Candelaria', 'Carepa', 'Cartagena', 'Cartago', 'Caucasia',
  'Chía', 'Chigorodó', 'Chiquinquirá', 'Ciénaga', 'Circasia', 'Corozal', 'Cúcuta',
  'Duitama', 'Dos Quebradas',
  'El Banco', 'El Carmen de Viboral', 'El Copey', 'Envigado', 'Espinal',
  'Facatativá', 'Florencia', 'Florida', 'Floridablanca', 'Funza', 'Fusagasugá',
  'Garzón', 'Ginebra', 'Girardot', 'Girón', 'Granada', 'Guadalajara de Buga',
  'Ibagué', 'Inírida', 'Ipiales', 'Itagüí',
  'La Ceja', 'La Dorada', 'La Estrella', 'La Plata', 'Leticia', 'Lorica',
  'Magangué', 'Maicao', 'Manizales', 'Manta', 'Medellín', 'Mitú', 'Mocoa',
  'Montelíbano', 'Montería', 'Mosquera',
  'Neiva', 'Necocli',
  'Ocaña',
  'Palmira', 'Pasto', 'Patía', 'Pereira', 'Piedecuesta', 'Pitalito', 'Popayán',
  'Puerto Asís', 'Puerto Berrío', 'Puerto Boyacá', 'Puerto Carreño', 'Puerto Colombia',
  'Puerto Inírida', 'Puerto Nariño', 'Puerto Tejada', 'Puerto Wilches',
  'Quibdó',
  'Riohacha', 'Rionegro',
  'Sabaneta', 'San Andrés', 'San Gil', 'San Juan del Cesar', 'Santa Marta',
  'Santa Rosa de Cabal', 'Sincelejo', 'Soacha', 'Socorro', 'Sogamoso', 'Soledad', 'Sonsón',
  'Tibaná', 'Tuluá', 'Tumaco', 'Tunja', 'Turbo',
  'Ubaté',
  'Valledupar', 'Villamaría', 'Villavicencio',
  'Yopal', 'Yumbo',
  'Zipaquirá',
].sort((a, b) => a.localeCompare(b, 'es'))
